name: house_predictor_ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  data-processing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Data Processing
        run: |
          python src/data/run_processing.py   --input data/raw/house_data.csv   --output data/processed/cleaned_house_data.csv

      
      - name: Run Feature Engineering
        run: |
          python src/features/engineer.py   --input data/processed/cleaned_house_data.csv   --output data/processed/featured_house_data.csv   --preprocessor models/trained/preprocessor.pkl
      

  model_training:
    needs: data-processing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download processed data 
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          pip install dagshub
          dagshub download --bucket jkhan2211/house-price-predictor data/processed/featured_house_data.csv"

      - name: Download preprocessor
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          pip install dagshub
          dagshub download --bucket jkhan2211/house-price-predictor "models/trained/preprocessor.pkl"

      - name: Run Model Training
        run: |
          python src/models/train.py  --input data/processed/featured_house_data.csv   --output models/trained/model.pkl   --preprocessor models/trained/preprocessor.pkl

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/trained/model.pkl